(function () {
  const template = {
    event: {
      occasion: 'Guldbryllup',
      coupleA: 'Kirsten',
      coupleB: 'Poul',
      date: 'Næste weekend',
      tone: 'Familievenlig',
      teamMode: 'bordhold',
      coupleRole: 'reveal-jury',
    },
    teams: [
      { id: 'bord-1', name: 'Bord 1', score: 0 },
      { id: 'bord-2', name: 'Bord 2', score: 0 },
      { id: 'bord-3', name: 'Bord 3', score: 0 },
    ],
    cases: [
      {
        id: 'case-1',
        format: 'one_story',
        title: 'Første besøg i køkkenet',
        activeTeamId: 'bord-1',
        storyOwner: 'Tobias',
        clues: ['Køleskabsmagnet', 'Dørhåndtag', 'Kaffekop'],
        prompt: 'Tobias kommer op. Han tager de tre ting en efter en og fortæller om første gang, han var hjemme hos æresparret.',
        question: 'Hvad gjorde Tobias næsten med det samme, da han trådte ind i køkkenet?',
        answer: 'Han åbnede køleskabet.',
        revealNote: 'Et stærkt førstegangsindtryk: direkte ind i familien og direkte i køleskabet.',
        options: [
          { clue: 'Køleskabsmagnet', story: 'Han åbnede køleskabet.', isCorrect: true },
          { clue: 'Dørhåndtag', story: 'Han gik forkert og åbnede kosteskabet.', isCorrect: false },
          { clue: 'Kaffekop', story: 'Han spildte kaffe, før han fik sagt hej.', isCorrect: false },
        ],
      },
      {
        id: 'case-2',
        format: 'three_stories',
        title: 'Tre versioner af samme aften',
        activeTeamId: 'bord-2',
        storyOwner: 'Mette',
        clues: ['Singleplade', 'Serviet', 'Foto fra forsamlingshuset'],
        prompt: 'Mette læser tre korte versioner op. Kun én er den rigtige historie fra aftenen.',
        question: 'Hvilken af de tre historier skete faktisk?',
        answer: 'Singlepladen: sangen fik Kirsten og Poul på dansegulvet.',
        revealNote: 'Hvis æresparret protesterer, må de synge den rigtige linje som bevis.',
        options: [
          { clue: 'Singleplade', story: 'Sangen fik Kirsten og Poul på dansegulvet.', isCorrect: true },
          { clue: 'Serviet', story: 'Poul skrev en tale bag på servietten.', isCorrect: false },
          { clue: 'Foto', story: 'Fotografen byttede rundt på to familier.', isCorrect: false },
        ],
      },
      {
        id: 'case-3',
        format: 'one_story',
        title: 'Kagen der ikke kom frem',
        activeTeamId: 'bord-3',
        storyOwner: 'Henrik',
        clues: ['Kagespade', 'Kvittering', 'Tomt kagefad'],
        prompt: 'Henrik fortæller en kort historie om en fest, hvor desserten var klar, men ingen kunne finde den.',
        question: 'Hvor var kagen gemt?',
        answer: 'I bagagerummet.',
        revealNote: 'Point for alle der også har glemt noget vigtigt i bilen.',
        options: [
          { clue: 'Kagespade', story: 'Kagen var allerede skåret ud.', isCorrect: false },
          { clue: 'Kvittering', story: 'Kagen blev aldrig købt.', isCorrect: false },
          { clue: 'Tomt fad', story: 'Kagen lå i bagagerummet.', isCorrect: true },
        ],
      },
      {
        id: 'case-4',
        format: 'one_story',
        title: 'Ferien med den forkerte afkørsel',
        activeTeamId: 'bord-1',
        storyOwner: 'Anne',
        clues: ['Vejkort', 'Termokop', 'Postkort fra Tyskland'],
        prompt: 'Anne fortæller, hvordan en forkert afkørsel blev til en hel ekstra oplevelse på ferien.',
        question: 'Hvad fandt de, da de kørte forkert?',
        answer: 'En lille kro med den bedste frokost.',
        revealNote: 'Når planen glipper, bliver det nogle gange den historie, alle husker.',
        options: [
          { clue: 'Vejkort', story: 'De fandt en kro med frokost.', isCorrect: true },
          { clue: 'Termokop', story: 'De måtte vende om efter kaffe.', isCorrect: false },
          { clue: 'Postkort', story: 'De endte i en helt anden by.', isCorrect: false },
        ],
      },
    ],
  };

  window.HLContent = { template };
})();
